### ISSUE TITLE
Error when running make_seagate_firmware.sh

### ISSUE THREAD

**Issue by mrneilsy** [bertofurth/Seagate-Central-Samba#2]
On a pi4b

Using the pre-compiled samba file, un-tar'd and folder renamed to cross

When I run ./make_seagate_firmware.sh ./Seagate-HS-update-201509160008F.img ./cross

I get the following, error, output

pi@naspi:~/Seagate-Central-Samba $ ./make_seagate_firmware.sh ./Seagate-HS-update-201509160008F.img ./cross

Creating new firmware image Seagate-Samba-Update-2022.0302.2314-S.img
Using base firmware ./Seagate-HS-update-201509160008F.img
Using samba directory ./cross
Enabling su access with default root password xxxxxxxxxxxxxxxxxxxxxxx

Filesystem      Size  Used Avail Use% Mounted on
/dev/root       7.1G  3.9G  2.9G  58% /
 Extract Seagate Firmware : 23:14:31
  Success: untar Seagate Firmware  23:14:35 See log_01_extract_firmware.log
  Success: unsquashfs  23:15:15 See log_02_unsquashfs.log
 Insert Samba software : 23:15:15
  Failure: copy libraries  23:18:04 Check log_03_cp_samba.log
cp: cannot overwrite non-directory 'squashfs-root/var/log' with directory './cross/var/log'
cp: cannot overwrite non-directory 'squashfs-root/var/lock' with directory './cross/var/lock'
cp: cannot overwrite non-directory 'squashfs-root/var/run' with directory './cross/var/run'

**Comment by switit** [comment]
I faced similar problem running the script using Alpine Linux on an old 32-bit pc. This was instantly solved by changing to run it using Archlinux on a 64-bit machine. Don't forget to install squashfs-tools on the machine.

**Comment by bertofurth** [comment]
Thanks so much for identifying this problem. As you've observed it seems that when building samba there are some subdirectories under /var/ that don't seem to gel well with the Seagate firmware.

I'll modify the build scripts to get rid of these and I'll update the pre-compiled version to remove these as well.

**Comment by bertofurth** [comment]
Thanks again for identifying this problem.

I've updated the precompiled samba to remove the directories that were causing the problem. Would you be inclined to try the procedure again with the new release?

https://github.com/bertofurth/Seagate-Central-Samba/releases/download/v1.0.1/seagate-central-samba-4.14.6-04-Mar-2022.tar.gz

Thanks very much!

Berto.

**Comment by mrneilsy** [comment]
Hi again. Sorry for the delay in testing / responding. I've been away for the weekend in a no signal area.

Anyway. Tested procedure and new samba file and it worked perfectly. Many thanks for the quick fix. 

I'll be having a go at the slot in kernel next then the utils. Thanks again for your sterling efforts.

Neil

**Comment by bertofurth** [comment]
No problems. Please make sure to let me know of any problems or suggest improvements.

Thanks again!

Berto.
